language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - pip install -U -r requirements.txt
before_success:
  - coverage erase
script:
  - py.test --durations=10 --cov changes --cov-report term-missing tests
after_success:
  - coverage combine
  - coveralls
  - codecov
  - ocular
